<?php
require_once __DIR__ . '/funciones.php';
require_once __DIR__ . '/layout.php';
if (local_mode() && !isset($_SESSION['usuario'])) {
    $_SESSION['usuario'] = '__local__';
    $_SESSION['rol'] = 'usuario';
    $_SESSION['guest'] = true;
}
require_login();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // A per-turn nonce also prevents a double click / retried POST from taking two turns.
    if (!hash_equals($_SESSION['turn_token'] ?? '', post('turn_token'))) redirect('GoblinDungeon.php');
    $_SESSION['turn_token'] = bin2hex(random_bytes(16));
    if (isset($_POST['enviar']) && !isset($_SESSION['partida'])) {
        if (!start_game(post('nombre'), post('clase'))) $_SESSION['notice'] = 'Escribe un nombre de hasta 80 bytes y escoge una clase.';
    } elseif (isset($_POST['accion'])) {
        advance_game();
    }
    redirect('GoblinDungeon.php');
}
$_SESSION['turn_token'] ??= bin2hex(random_bytes(16));
page_start('La mazmorra');
?>
<div id="contPrincipal"><section id="contMenu">
<?php if (!empty($_SESSION['notice'])): ?><p role="status"><?= e($_SESSION['notice']) ?></p><?php unset($_SESSION['notice']); endif; ?>
<?php if (!isset($_SESSION['xogador'])): ?>
<h1>Entra en Goblin Dungeon</h1>
<p>Cinco goblins, encuentros inesperados y una sola vida. Elige tu clase.</p>
<form method="post" action="GoblinDungeon.php">
<?= csrf_field() ?><input type="hidden" name="turn_token" value="<?= e($_SESSION['turn_token']) ?>">
<label>Clase <select name="clase"><option value="guerrero">Guerrero</option><option value="paladin">Paladín</option><option value="picaro">Pícaro</option></select></label>
<p>Guerrero: equilibrado. Paladín: resistente. Pícaro: letal y frágil.</p>
<label>Nombre del personaje <input name="nombre" required maxlength="40" autocomplete="off"></label>
<p><button name="enviar" value="1">Comenzar</button></p>
</form></section>
<?php else:
$player = $_SESSION['xogador'][0];
$game = $_SESSION['partida'][0];
echo $_SESSION['scene'] ?? ''; // Only markup generated by the game, never user input.
?>
</section><div id="contSecundario"><section id="contInterfaz"><div id="contEstadisticas">
<h2><?= e($player->getNombre()) ?></h2>
<p><?= e($player->getClase()) ?></p>
<p>Vida: <?= e(max(0, $player->getVida())) ?> · Ataque: <?= e($player->getAtaque()) ?></p>
<p>Defensa: <?= e($player->getDefensa()) ?> · Esquiva: <?= e($player->getEsquiva()) ?> %</p>
<?php if (isset($_SESSION['goblin'])): ?><p>Vida del goblin: <?= e(max(0, $_SESSION['goblin'][0]->getVidaGoblin())) ?></p><?php endif; ?>
</div><div id="contOpciones"><form method="post" action="GoblinDungeon.php">
<?= csrf_field() ?><input type="hidden" name="turn_token" value="<?= e($_SESSION['turn_token']) ?>">
<button name="accion" value="1"><?=
$player->getVida() <= 0 ? 'Volver al inicio' :
($game->getTurno() === 14 ? 'Guardar victoria y volver' : (isset($_SESSION['goblin']) ? 'Atacar' : 'Continuar'))
?></button></form></div></section>
<section id="contInventario"><h2>Inventario</h2><ul>
<?php foreach ($player->getInventario() as $item): ?><li><?= e($item) ?></li><?php endforeach; ?>
</ul></section></div>
<?php endif; ?>
</div>
<?php page_end(); ?>
