<?php
declare(strict_types=1);
error_reporting(E_ALL);
set_error_handler(function ($level, $message, $file, $line) { throw new ErrorException($message, 0, $level, $file, $line); });
putenv('GOBLIN_DATA_DIR=' . sys_get_temp_dir() . '/goblin-test-' . bin2hex(random_bytes(8)));
require __DIR__ . '/../GoblinDungeon/funciones.php';
function check(bool $ok, string $message): void {
    if (!$ok) throw new RuntimeException($message);
    echo "PASS: $message\n";
}
$_SESSION = ['usuario' => 'tester'];
check(!start_game('test', 'inventada'), 'Invalid classes are rejected');
check(start_game('<script>alert(1)</script>', 'guerrero'), 'Character creation');
check(e($_SESSION['xogador'][0]->getNombre()) === '&lt;script&gt;alert(1)&lt;/script&gt;', 'Character names are escaped');
advance_game();
check($_SESSION['goblin'][0]->getNombreGoblin() === 'Goblin Novato', 'First enemy appears');
$life = $_SESSION['xogador'][0]->getVida();
advance_game();
check($_SESSION['partida'][0]->getTurno() === 2 && !isset($_SESSION['goblin']), 'Victory is immediate');
check($_SESSION['xogador'][0]->getVida() === $life, 'Defeated enemy cannot counterattack');
advance_game();
check($_SESSION['partida'][0]->getTurno() === 3, 'Event follows combat');
$state = serialize($_SESSION);
$scene = $_SESSION['scene'];
check($scene !== '', 'Event output is cached');
check(serialize($_SESSION) === $state, 'Reading scene does not mutate state');
$_SESSION['xogador'][0]->setVida(100);
$_SESSION['partida'][0]->esquiva(5, 0, 100, 1000);
check($_SESSION['xogador'][0]->getVida() === 100, 'Defence cannot heal the player');
$player = $_SESSION['xogador'][0];
$player->setVida(0);
render_turn();
check(str_contains($_SESSION['scene'], 'GAME OVER'), 'Death is displayed immediately');
advance_game();
check(!isset($_SESSION['partida'], $_SESSION['xogador']), 'Restart clears the run');
start_game('Champion', 'paladin');
$_SESSION['xogador'][0]->setAtaque(1000);
$_SESSION['xogador'][0]->setVida(10000);
for ($i = 0; $i < 30 && $_SESSION['partida'][0]->getTurno() !== 14; $i++) advance_game();
check($_SESSION['partida'][0]->getTurno() === 14, 'All five fights reach final victory');
$player = $_SESSION['xogador'][0];
$inventory = $player->getInventario();
$id = $_SESSION['run_id'];
advance_game();
check(count(Dao::wins('tester')) === 1, 'Victory persists');
Dao::saveWin($id, 'tester', $player);
check(count(Dao::wins('tester')) === 1, 'Saving same victory twice is idempotent');
check($player->getInventario() === $inventory && is_array($inventory), 'Saving preserves inventory type');
check(Dao::wins('other') === [], 'Wins belong to their user');
check(Dao::register('Tester', 'password & <123>'), 'Registration');
check(!Dao::register('tester', 'different'), 'Duplicate names are case insensitive');
$user = Dao::findUser('TESTER');
check(password_verify('password & <123>', $user['password']), 'Passwords preserve special characters and use password_hash');
check(!password_verify('wrong', $user['password']), 'Wrong passwords fail');
for ($i = 0; $i < 20; $i++) check(Dao::loginAllowed('127.0.0.1'), 'Login budget available');
check(!Dao::loginAllowed('127.0.0.1'), 'Login rate limit shared in database');
Dao::deleteUser('Tester');
check(Dao::findUser('Tester') === null && Dao::wins('tester') === [], 'Delete removes account and victories');
echo "Regression suite passed.\n";
