[PHP]
display_errors=Off
log_errors=On
error_reporting=E_ALL
expose_php=Off
extension_dir="${GOBLIN_EXTENSION_DIR}"
extension=pdo_sqlite
upload_max_filesize=200K
post_max_size=1M
max_execution_time=30
session.use_strict_mode=1
session.use_only_cookies=1
session.gc_maxlifetime=2592000
